Sender: LSF System <lsfadmin@gpu16>
Subject: Job 79210: <cityscapes_baseline> in cluster <cluster1> Exited

Job <cityscapes_baseline> was submitted from host <login02> by user <wkyang> in cluster <cluster1> at Wed Sep 15 17:54:07 2021
Job was executed on host(s) <6*gpu16>, in queue <gpu_v100>, as user <wkyang> in cluster <cluster1> at Wed Sep 15 17:54:09 2021
</seu_share/home/wkyang> was used as the home directory.
</seu_share/home/wkyang/code/2021/sep/15.sep/DeepLab-v3-plus-cityscapes> was used as the working directory.
Started at Wed Sep 15 17:54:09 2021
Terminated at Wed Sep 15 17:54:48 2021
Results reported at Wed Sep 15 17:54:48 2021

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#!/bin/bash

#BSUB -J cityscapes_baseline
#BSUB -q gpu_v100
#BSUB -gpu "num=2:mode=exclusive_process:aff=yes"

conda activate py37
python -m torch.distributed.launch --nproc_per_node=2 train.py


------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   37.00 sec.
    Max Memory :                                 6508 MB
    Average Memory :                             1186.37 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              14
    Max Threads :                                48
    Run time :                                   41 sec.
    Turnaround time :                            41 sec.

The output (if any) follows:


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


0
torch.Size([19, 415, 564]) torch.Size([19, 415, 564])
torch.Size([19, 28, 715]) torch.Size([19, 28, 715])
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    train(args=args)
  File "train.py", line 124, in train
    mse, sym_ce, mid_mse, mid_ce, mid_l1, ce = Criterion(outputs, overlap, flip, lb)
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/seu_share/home/wkyang/code/2021/sep/15.sep/DeepLab-v3-plus-cityscapes/loss.py", line 159, in forward
    mse, _, _, sym_ce, ce = new_ssp_loss.forward(self, outputs[-1], overlap, flips, labels)
  File "/seu_share/home/wkyang/code/2021/sep/15.sep/DeepLab-v3-plus-cityscapes/loss.py", line 56, in forward
    ce_loss_1_2 = self.ce_loss(img_1.unsqueeze(0), img_2_label)
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/seu_share/home/wkyang/code/2021/sep/15.sep/DeepLab-v3-plus-cityscapes/loss.py", line 194, in forward
    thresh = self.thresh if sorteds[self.n_min]<self.thresh else sorteds[self.n_min]
IndexError: index 147456 is out of bounds for dimension 0 with size 20020
torch.Size([19, 554, 768]) torch.Size([19, 554, 768])
torch.Size([19, 703, 208]) torch.Size([19, 703, 208])
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    train(args=args)
  File "train.py", line 124, in train
    mse, sym_ce, mid_mse, mid_ce, mid_l1, ce = Criterion(outputs, overlap, flip, lb)
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/seu_share/home/wkyang/code/2021/sep/15.sep/DeepLab-v3-plus-cityscapes/loss.py", line 159, in forward
    mse, _, _, sym_ce, ce = new_ssp_loss.forward(self, outputs[-1], overlap, flips, labels)
  File "/seu_share/home/wkyang/code/2021/sep/15.sep/DeepLab-v3-plus-cityscapes/loss.py", line 56, in forward
    ce_loss_1_2 = self.ce_loss(img_1.unsqueeze(0), img_2_label)
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/seu_share/home/wkyang/code/2021/sep/15.sep/DeepLab-v3-plus-cityscapes/loss.py", line 194, in forward
    thresh = self.thresh if sorteds[self.n_min]<self.thresh else sorteds[self.n_min]
IndexError: index 147456 is out of bounds for dimension 0 with size 146224
Traceback (most recent call last):
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/seu_share/home/wkyang/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/seu_share/home/wkyang/anaconda3/bin/python', '-u', 'train.py', '--local_rank=1']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
